# Generated by Django 5.2.5 on 2025-09-30 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-budget_year', '-budget_month', '-date_created']},
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'type', 'budget_year', 'budget_month')},
        ),
    ]
