# Generated by Django 5.2.5 on 2025-09-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeorexpense',
            name='vendor',
            field=models.CharField(default='', max_length=32),
        ),
    ]
