# Generated by Django 5.2.5 on 2025-10-14 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_carry_over_defaults(apps, schema_editor):
    Budget = apps.get_model("finance", "Budget")
    Budget.objects.filter(type__in=["SAVINGS", "INVESTING"]).update(
        allow_carry_over=True
    )


def reverse_carry_over_defaults(apps, schema_editor):
    Budget = apps.get_model("finance", "Budget")
    Budget.objects.filter(type__in=["SAVINGS", "INVESTING"]).update(
        allow_carry_over=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_budget_options_budget_budget_month_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="allow_carry_over",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="budget",
            name="carried_over_amount_in_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_carry_over_defaults, reverse_carry_over_defaults),
        migrations.CreateModel(
            name="InternalTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_in_cents", models.PositiveIntegerField()),
                ("transfer_date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "destination_budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="finance.budget",
                    ),
                ),
                (
                    "source_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transfers",
                        to="finance.budget",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transfer_date", "-date_created"],
                "indexes": [
                    models.Index(
                        fields=["source_budget"], name="finance_int_source__4abb9c_idx"
                    ),
                    models.Index(
                        fields=["destination_budget"],
                        name="finance_int_destina_9ac359_idx",
                    ),
                ],
            },
        ),
    ]
