# Generated by Django 5.2.5 on 2025-10-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget_allow_carry_over_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_reminder_enabled', models.BooleanField(default=True)),
                ('weekly_summary_enabled', models.BooleanField(default=True)),
                ('monthly_summary_enabled', models.BooleanField(default=True)),
                ('yearly_summary_enabled', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('WEEKLY_REMINDER', 'Weekly Reminder'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('YEARLY_SUMMARY', 'Yearly Summary')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('email_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user'], name='finance_ema_user_id_587ddb_idx'), models.Index(fields=['email_type'], name='finance_ema_email_t_7d7e4d_idx'), models.Index(fields=['sent_at'], name='finance_ema_sent_at_fc6c8b_idx')],
            },
        ),
    ]
